[Start of MSG File]
[Message Properties]
  - Sender: Anne Howard <ahoward@oscp.exam>
  - Recipients: Sasha Payne <spayne@oscp.exam>
  - Subject: Access
  - Date: 2023-09-22 08:47:03
  - Message ID: <50o8v3al70ht7v1a@oscp.exam>
  - MIME Version: 1.0
  - ...
[Message Body]
  Hi Sasha,  

  Rob from IT mentioned you need remote access to our servers this weekend, ahead of the new product launch. 
  The password will be our default one, used after a password reset: Voltaic1992

  Please let me know if you need any assistance, I do have some availability.  

  Best regards,
  Anne
[Attachments]
  - signature.jpg
  - ...
[End of MSG File]
