[Start of MSG File]
[Message Properties]
  - Sender: Anne Howard <ahoward@oscp.exam>
  - Recipients: Manuel Richmond <mrichmond@oscp.exam>
  - Subject: Potential Customer
  - Date: 2023-09-21 12:42:28
  - Message ID: <51aa802cp70ht543y@oscp.exam>
  - MIME Version: 1.0
  - ...
[Message Body]
  Hey Manny, 

  I just bumped into a collage friend, who is now the CEO of LeetRus!
  She mentioned that they'd like to fit out their seven office premises with solar solutions, please could you arrange a presentation date with them ASAP?

  This would be a massive contract for us, so please do your best to impress. :)

  Best regards,
  Anne
[Attachments]
  - leetRus.vcf
  - signature.jpg
  - ...
[End of MSG File]
