[Start of MSG File]
[Message Properties]
  - Sender: Anne Howard <ahoward@oscp.exam>
  - Recipients: Mica Garret <mgarret@oscp.exam>
  - Subject: Welcome
  - Date: 2023-09-20 09:34:56
  - Message ID: <51aa892cp70hv543f@oscp.exam>
  - MIME Version: 1.0
  - ...
[Message Body]
  Hi Mica,

  Just wanted to say hello, and welcome you to the company!

  Please see the Company Policy attached, feel free to reach out to HR if you have any queries or concerns. 

  I will ask Letisha to set up a lunch meeting next week, so we can discuss your first projects. 

  Best regards,
  Anne
[Attachments]
  - company-policy.pdf
  - signature.jpg
  - ...
[End of MSG File]
