[Start of MSG File]
[Message Properties]
  - Sender: Anne Howard <ahoward@oscp.exam>
  - Recipients: James Oliver <jolver@oscp.exam>
  - Subject: Potential Customer
  - Date: 2023-09-21 16:21:59
  - Message ID: <50o9802cp70ht7v1a@oscp.exam>
  - MIME Version: 1.0
  - ...
[Message Body]
  Hi James,  

  As mentioned in this morning's meeting, there has been a recall on a batch of our panels. Please check where these were installed, so that we can get them cswitched out. 
  I want to preempt any potential complaints. 

  Please keep me updated on your progress. 

  Best regards,
  Anne
[Attachments]
  - signature.jpg
  - ...
[End of MSG File]
